### ISSUE TITLE
Add a gameid blacklist

### ISSUE THREAD

**Issue by narutards** [10101000/Steam-AutoCraft#1]
It would be really useful if you could add a blacklist feature for game ids. With the steam summer sale just around the corner we'll soon be getting sale cards again and I really don't want to craft the summer set right at the start of the sale.
I'd like to craft all sets except for the summer sale one.

**Comment by 10101000** [comment]
This will require some type of settings mechanism, something that I've wanted to do for some time. I'll see what I can do.

**Comment by narutards** [comment]
That would be really awesome. Even better if you could finish until the summer sale. My mouse will be forever grateful. ;)

**Comment by titoncio** [comment]
ID:
480730

**Comment by 10101000** [comment]
Hi, I think that we're almost ready, would you mind helping me test this new blacklist feature? You can get the latest version 1.4.5 at https://www.10101000.net/Steam-AutoCraft.user.js.

**Comment by narutards** [comment]
I'd love to ... I crafted all my badges akready though and then I fucked up my authenticator. -.- So I can't get any new cards atm. As soon as I can again I will test the script, sure.

**Comment by tekanoma** [comment]
I found a problem with it, it only works as long as the badge is first on the page if you want to blacklist it, for example if you want to blacklist the fourth game on the list, it requires badge one to four to be listed, I guess this isn't a huge problem as the blacklist was primarily created to block the sale badges which appear at the top of the badge page when revealed. I also tried crafting a badge from the badges own page and it still crafted it but Id say that should be an area that isn't affected by the blacklist since it requires the user to go to the page and hit the button so they would fully know they are crafting the badge

**Comment by 10101000** [comment]
Thanks for your help! I'm all out of badges myself so I've not been able to test with 2 pages of craft-able badges. Regarding the badge details page, I've intentionally left the blacklisting out of the gamecard pages as a manual override I guess.

The present "looping" relies on steamcommunity.com to properly render the badge elements on the page where the first div is a craft-able game. To blacklist games, we build a regex to match IDs and then loop over the badges on the present page. If matched, we skip it by removal of the "Craft Badge" button because we depend on that button to determine the craft-able state.

This process is handled by the `checkBlacklist()` function which is executed when we add the autocraft button to the page and also when clicking the autocraft button to begin crafting. I am a little confused as to why this would break if badges are on page 2 because once we craft all of page 1, the function should handle any new items on refresh.

**Comment by 10101000** [comment]
Hi, I've released 1.4.6 to disable execution from any page other than page one.
