### ISSUE TITLE
Greasemonkey

### ISSUE THREAD

**Issue by Jostino** [10101000/Steam-AutoCraft#13]
Hello there,
after the manual installation (greasemoneky didn't recognize automatically this script) the script didn't show me the button in the badge zone. I tried it with tempermoneky and worked well...

**Comment by kikusko** [comment]
poslite

**Comment by 10101000** [comment]
Hi,

Much has changed with Firefox 57+ including the extension system. Due to these changes the Greasemonkey extension has been almost completely re-written. I believe that I've identified the problem and plan to release a new version soon. I've also noticed that the HTML/CSS formatting has changed as well. I'm investigating a fix for this too.

**Comment by 10101000** [comment]
This should be fixed. To install with Greasemonkey 4.x try: https://rawgit.com/10101000/Steam-AutoCraft/master/Steam-AutoCraft.user.js

Please confirm.

**Comment by Bagus23** [comment]
confirmed, tested with 20 badges with Firefox 57+

thank you.

**Comment by 10101000** [comment]
Great, thanks!
