### ISSUE TITLE
Script keeps refreshing the game badge page

### ISSUE THREAD

**Issue by narutards** [10101000/Steam-AutoCraft#2]
After clicking the craft button on the badge page steam redirects to the game badge page. The script then continues to reload the game badge page over and over again.

**Comment by narutards** [comment]
I fixed this for myself quick and dirty by replacing line #96 with the following:

setTimeout(function(){ window.location.href = jQuery('div').find('.profile_small_header_text a.whiteLink').attr('href') + '/badges/'; }, craftRefreshTimeoutms);

**Comment by 10101000** [comment]
I've tested the script in Firefox and Chrome and never encountered this problem. Can you provide more information? Like browser version and plugins are you using? Perhaps there is a conflict with another plugin.

The idea behind using window.location.reload(true) is so that we stay on the same page that we're on until jQuery('.badge_craft_button').length equals 0:
`setTimeout(function(){` window.location.reload(true); }, craftRefreshTimeoutms);`

The modification that you've provided is problematic because it not only breaks execution from the gamecard page, it also greatly increases the overhead and number of requests that you make to craft everything because we go back to badges after crafting each badge on the gamecard page. We need to be reloading the gamecard page to "loop" until no further badges can be crafted.

**Comment by tekanoma** [comment]
yeah I had this problem as well, it would keep refreshing the same page after crafting the badge to its highest possible level with the cards I had and never go back to the badge page, I ended up having to go to each badge and doing it from there and it never continued to refresh itself when done directly from the badge page. I'm using Vivaldi but its pretty much a different version of chrome itself so I don't think it would be the problem, and I do have enhanced steam and steam ninja installed which do modify the badge pages but I don't think they would prevent the script from going back to the badge page and causing it to reload the page indefinitely

**Comment by narutards** [comment]
Latest firefox and enhanced steam as well as steam trade matcher extensions. I really doubt this is caused by an extension conflict.

But yes, the overhead with my "fix" is massive. It was still the easiest and quickest way for me to make it do what I wanted it to do for me.

**Comment by 10101000** [comment]
I've identified the issue, and hope to have a fix soon.

**Comment by 10101000** [comment]
If you're willing to help me test these changes, please try the alpa version at https://www.10101000.net/Steam-AutoCraft.user.js. Note that the settings haven't been fully implemented but I've re-written the core logic and so far I've been unable to re-produce this issue.

**Comment by tekanoma** [comment]
It now backs out to the badge page successfully and doesn't go into a reloading loop, so far it seems to be working completely for me

**Comment by 10101000** [comment]
Thanks! I appreciate your feedback. It also seems to load faster now for me. I'm working to get the settings functional, then the game id blacklist mechanism, then I'll commit and release.

**Comment by 10101000** [comment]
I've updated the alpha version to 1.4.2, I believe that this is ready to go. Settings, crafting, and blacklisting are fully functional according to my limited testing.

**Comment by 10101000** [comment]
This should be fixed, please re-open if you see it again.
