### ISSUE TITLE
Userscript URL matching

### ISSUE THREAD

**Issue by Royalgamer06** [10101000/Steam-AutoCraft#3]
You should use 

```
// @incude       *://steamcommunity.com/*/gamecards*
// @incude       *://steamcommunity.com/*/badges*
```

Instead of 

```
// @match        *://steamcommunity.com/*/gamecards/*
// @match        *://steamcommunity.com/*/badges/*
```

Because otherwise, it didn't work for me.

**Comment by 10101000** [comment]
Hi, can you provide more information? Which browser and plugin are you using? Are you using any additional Steam userscripts/plugins that could cause a conflict? `@match` is valid syntax and works just fine for myself and many others. We also explicitly only want to load for gamecards/* not gamecards*. For the badges page, it won't load without the trailing slash. I've not found any case where Steam doesn't include this trailing slash in links. Are you linking directly to it? If so, perhaps just add the slash? `@match` is also purported to be "safer" due to its wildcard handling. For more information please read:

https://wiki.greasespot.net/Metadata_Block#.40match
https://tampermonkey.net/documentation.php#_match
https://developer.chrome.com/extensions/match_patterns

**Comment by Royalgamer06** [comment]
http://example.com !== http://example.com/
I'm using Google Chrome. It would be very remarkable if this is caused by an extension or userscript. Your userscript just doesn't match the URL pattern (without "/") and therefore doesn't load at all (I checked in list with loaded scripts).

**Comment by Royalgamer06** [comment]
Let me clarify more:
The URL "http://steamcommunity.com/id/royalgamer06/badges/" loads the userscript. 
The URL "http://steamcommunity.com/id/royalgamer06/badges" does NOT load the userscript.
BTW, /gamecards URL is obsolete, it redirects to the /badges URL.
If you don't like the use of @include, use @match then. It doesn't really matter.

**Comment by 10101000** [comment]
Yes, this behavior is by design. We want to limit where the script is loaded to **exactly** the badges & gamecards pages. We don't want to load for context paths that could be used by Steam in the future like 

`http://steamcommunity.com/id/user/badges_steam`

You might want to ask yourself why you're the only user who has reported this issue. You're either linking directly to the URL without trailing slash (why?) or something is wrong with your client/proxy server which might be removing the trailing slash. Take a look at the HTML links on the steamcommunity.com website and notice that they have the trailing slash:

`<a class="submenuitem" href="http://steamcommunity.com/id/user/badges/">Badges</a>`

BTW, you're entirely incorrect about /gamecards. Try clicking into a game from the badges page like:

`<a class="badge_row_overlay" href="http://steamcommunity.com/id/user/gamecards/264280/"></a>`

**Comment by Royalgamer06** [comment]
If you really want to be that precise, why don't you use regex?
`//@include /^http(s)*\:\/\/steamcommunity\.com\/(id\/.+|profiles\/7656119[0-9]{10})\/(badges|badges\/.*|gamecards\/.+)$/`

**Comment by 10101000** [comment]
I want to keep it simple. Adding a complex regex increases overhead. Feel free to fork my project, add whatever you want and maintain it yourself. I won't be changing this. Thanks.

**Comment by 10101000** [comment]
Alright, I've changed my mind. I'll look at using `@include` with a regular expression.

**Comment by 10101000** [comment]
I've opted to use the following regex:

`// @include      /^http[s]?:\/\/steamcommunity.com\/+(id\/+[A-Za-z0-9$-_.+!*'(),]+|profiles\/+[0-9]+)\/+(badges[\/]?|gamecards\/+[0-9]+[\/]?)$/`

Would you mind testing version **1.4.7** from [https://www.10101000.net/Steam-AutoCraft.user.js](here) before I commit the change? Thanks!

**Comment by 10101000** [comment]
Done! Thanks.
